# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aaaaaaaaaaa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PairGame(object):
    def setupUi(self, PairGame):
        PairGame.setObjectName("PairGame")
        PairGame.resize(1294, 673)
        PairGame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        PairGame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        PairGame.setStyleSheet("background:qlineargradient(spread:pad, x1:0.505, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 144, 144, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(PairGame)
        self.centralwidget.setObjectName("centralwidget")
        self.BTN1 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN1.setGeometry(QtCore.QRect(50, 70, 150, 150))
        self.BTN1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.BTN1.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN1.setText("")
        self.BTN1.setObjectName("BTN1")
        self.BTN2 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN2.setGeometry(QtCore.QRect(250, 70, 150, 150))
        self.BTN2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN2.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN2.setText("")
        self.BTN2.setObjectName("BTN2")
        self.BTN4 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN4.setGeometry(QtCore.QRect(50, 300, 150, 150))
        self.BTN4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN4.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN4.setText("")
        self.BTN4.setObjectName("BTN4")
        self.BTN5 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN5.setGeometry(QtCore.QRect(250, 300, 150, 150))
        self.BTN5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN5.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN5.setText("")
        self.BTN5.setObjectName("BTN5")
        self.BTN3 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN3.setGeometry(QtCore.QRect(450, 70, 150, 150))
        self.BTN3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN3.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN3.setText("")
        self.BTN3.setObjectName("BTN3")
        self.BTN6 = QtWidgets.QPushButton(self.centralwidget)
        self.BTN6.setGeometry(QtCore.QRect(450, 300, 150, 150))
        self.BTN6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN6.setStyleSheet("background:rgb(170, 170, 255)")
        self.BTN6.setText("")
        self.BTN6.setObjectName("BTN6")
        self.start_again = QtWidgets.QPushButton(self.centralwidget)
        self.start_again.setGeometry(QtCore.QRect(940, 510, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_again.setFont(font)
        self.start_again.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_again.setStyleSheet("font: 30pt \"Wide Latin\";\n"
"background:rgb(255, 139, 145)")
        self.start_again.setObjectName("start_again")
        self.cat1_1 = QtWidgets.QLabel(self.centralwidget)
        self.cat1_1.setGeometry(QtCore.QRect(700, 70, 150, 150))
        self.cat1_1.setText("")
        self.cat1_1.setPixmap(QtGui.QPixmap("cat1.jpg"))
        self.cat1_1.setScaledContents(True)
        self.cat1_1.setObjectName("cat1_1")
        self.cat3_5 = QtWidgets.QLabel(self.centralwidget)
        self.cat3_5.setGeometry(QtCore.QRect(900, 300, 150, 150))
        self.cat3_5.setText("")
        self.cat3_5.setPixmap(QtGui.QPixmap("cat3.jpg"))
        self.cat3_5.setScaledContents(True)
        self.cat3_5.setObjectName("cat3_5")
        self.cat2_4 = QtWidgets.QLabel(self.centralwidget)
        self.cat2_4.setGeometry(QtCore.QRect(700, 300, 150, 150))
        self.cat2_4.setText("")
        self.cat2_4.setPixmap(QtGui.QPixmap("cat2.jpg"))
        self.cat2_4.setScaledContents(True)
        self.cat2_4.setObjectName("cat2_4")
        self.cat1_6 = QtWidgets.QLabel(self.centralwidget)
        self.cat1_6.setGeometry(QtCore.QRect(1100, 300, 150, 150))
        self.cat1_6.setText("")
        self.cat1_6.setPixmap(QtGui.QPixmap("cat1.jpg"))
        self.cat1_6.setScaledContents(True)
        self.cat1_6.setObjectName("cat1_6")
        self.cat2_2 = QtWidgets.QLabel(self.centralwidget)
        self.cat2_2.setGeometry(QtCore.QRect(900, 70, 150, 150))
        self.cat2_2.setText("")
        self.cat2_2.setPixmap(QtGui.QPixmap("cat2.jpg"))
        self.cat2_2.setScaledContents(True)
        self.cat2_2.setObjectName("cat2_2")
        self.cat3_3 = QtWidgets.QLabel(self.centralwidget)
        self.cat3_3.setGeometry(QtCore.QRect(1100, 70, 150, 150))
        self.cat3_3.setText("")
        self.cat3_3.setPixmap(QtGui.QPixmap("cat3.jpg"))
        self.cat3_3.setScaledContents(True)
        self.cat3_3.setObjectName("cat3_3")
        self.victory = QtWidgets.QLabel(self.centralwidget)
        self.victory.setGeometry(QtCore.QRect(50, 480, 541, 161))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(46)
        self.victory.setFont(font)
        self.victory.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.victory.setObjectName("victory")
        self.sscoore = QtWidgets.QLabel(self.centralwidget)
        self.sscoore.setGeometry(QtCore.QRect(630, 500, 261, 121))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(25)
        self.sscoore.setFont(font)
        self.sscoore.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.sscoore.setObjectName("sscoore")
        PairGame.setCentralWidget(self.centralwidget)

        self.retranslateUi(PairGame)
        QtCore.QMetaObject.connectSlotsByName(PairGame)

        self.victory.hide()
        self.cat3_3.hide()
        self.cat2_2.hide()
        self.cat1_6.hide()
        self.cat2_4.hide()
        self.cat3_5.hide()
        self.cat1_1.hide()
        self.victory.hidden = True
        self.cat3_3.hidden = True
        self.cat2_2.hidden = True
        self.cat1_6.hidden = True
        self.cat2_4.hidden = True
        self.cat3_5.hidden = True
        self.cat1_1.hidden = True

        self.BTN1.clicked.connect(self.sh_cat1_1)
        self.BTN2.clicked.connect(self.sh_cat2_2)
        self.BTN3.clicked.connect(self.sh_cat3_3)
        self.BTN4.clicked.connect(self.sh_cat2_4)
        self.BTN5.clicked.connect(self.sh_cat3_5)
        self.BTN6.clicked.connect(self.sh_cat1_6)
        self.start_again.clicked.connect(self.sc1)

    def retranslateUi(self, PairGame):
        _translate = QtCore.QCoreApplication.translate
        PairGame.setWindowTitle(_translate("PairGame", "MainWindow"))
        self.start_again.setText(_translate("PairGame", "CHECK"))
        self.victory.setText(_translate("PairGame", "VICTORY"))
        self.sscoore.setText(_translate("PairGame", "Score: "))

    def sh_cat1_1(self):
        if self.cat1_1.hidden:
            self.cat1_1.show()
            self.cat1_1.hidden = False
        else:
            self.cat1_1.hide()
            self.cat1_1.hidden = True

    def sh_cat2_2(self):
        if self.cat2_2.hidden:
            self.cat2_2.show()
            self.cat2_2.hidden = False
        else:
            self.cat2_2.hide()
            self.cat2_2.hidden = True

    def sh_cat3_3(self):
        if self.cat3_3.hidden:
            self.cat3_3.show()
            self.cat3_3.hidden = False
        else:
            self.cat3_3.hide()
            self.cat3_3.hidden = True

    def sh_cat2_4(self):
        if self.cat2_4.hidden:
            self.cat2_4.show()
            self.cat2_4.hidden = False
        else:
            self.cat2_4.hide()
            self.cat2_4.hidden = True

    def sh_cat3_5(self):
        if self.cat3_5.hidden:
            self.cat3_5.show()
            self.cat3_5.hidden = False
        else:
            self.cat3_5.hide()
            self.cat3_5.hidden = True

    def sh_cat1_6(self):
        if self.cat1_6.hidden:
            self.cat1_6.show()
            self.cat1_6.hidden = False
        else:
            self.cat1_6.hide()
            self.cat1_6.hidden = True

    def sc1(self):
        if not self.cat1_1.hidden and not self.cat1_6.hidden and not self.cat2_2.hidden and not self.cat2_4.hidden and not self.cat3_5.hidden and not self.cat3_3.hidden:
            self.victory.show()
            self.victory.hidden = False
            self.sscoore.setText('Score: 3')
        elif not self.cat1_1.hidden and not self.cat1_6.hidden and not self.cat2_2.hidden and not self.cat2_4.hidden:
            self.sscoore.setText('Score: 2')
            self.victory.hide()
            self.victory.hidden = True
        elif not self.cat1_1.hidden and not self.cat1_6.hidden and not self.cat3_5.hidden and not self.cat3_3.hidden:
            self.sscoore.setText('Score: 2')
            self.victory.hide()
            self.victory.hidden = True
        elif not self.cat3_3.hidden and not self.cat3_5.hidden and not self.cat2_2.hidden and not self.cat2_4.hidden:
            self.sscoore.setText('Score: 2')
            self.victory.hide()
            self.victory.hidden = True
        elif not self.cat1_1.hidden and not self.cat1_6.hidden:
            self.sscoore.setText('Score: 1')
            self.victory.hide()
            self.victory.hidden = True
        elif not self.cat2_2.hidden and not self.cat2_4.hidden:
            self.sscoore.setText('Score: 1')
            self.victory.hide()
            self.victory.hidden = True
        elif not self.cat3_3.hidden and not self.cat3_5.hidden:
            self.sscoore.setText('Score: 1')
            self.victory.hide()
            self.victory.hidden = True
        else:
            self.victory.hide()
            self.victory.hidden = True
            self.sscoore.setText('Score: 0')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PairGame = QtWidgets.QMainWindow()
    ui = Ui_PairGame()
    ui.setupUi(PairGame)
    PairGame.show()
    sys.exit(app.exec_())
